name: phonics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - nb_conda
  - pip
  - pip:
    - cython==0.29.15                 # ability to natively call C functions
    - joblib==0.13.2                  # persist to disk transparently
    - tabulate==0.8.3                 # pretty print python dataframes
    - pandas==0.25.0                  # data analysis and manipulation tool
    - Keras==2.2.4                    # high-level neural networks API
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - numpy==1.16.4                   # general-purpose array-processing package
    - numpydoc==0.9.1                 # sphinx extension to support docstrings in Numpy format
    - tensorflow==1.13.1              # library for numerical computation API from google
    - tensorflow-estimator==1.13.0    # wraps a TF model
    - xlrd==1.2.0                     # Microsoft Excel data extraction library
    - scikit-learn==0.21.2            # A set of python modules for machine learning and data mining
    - scipy==1.3.0                    # engineering ecosystem; depends on numpy
    - jsonpickle==1.3                 # serialize any arbitrary object graph into JSON
    - plac==1.1.3                     # simple command line arguments parser
    - fastapi==0.52.0                 # web framework for building APIs with Python
    - uvicorn==0.11.3                 # an ASGI server (includes gunicorn)
    - uuid                            # UUID generator
    - mysql-connector-python==8.0.19  # MySQL Connector
    - cryptography==2.9               # For credentials decryption
    - pytest-xdist==1.30              # Run unit tests in parallel
    - pytest==5.2                     # Run unit tests
    - google-ngram-downloader==4.0.1  # access google ngrams
